require("jojo.plugins-setup") 
require("jojo.core.options") 
require("jojo.core.keymaps") 
require("jojo.core.colorscheme") 
require("jojo.plugins.nvim-tree")
require("jojo.plugins.lualine") 
require("jojo.plugins.telescope")
require("jojo.plugins.nvim-cmp")
require("jojo.plugins.lsp.mason")
require("jojo.plugins.lsp.lspsaga")
require("jojo.plugins.lsp.lspconfig")
require("jojo.plugins.treesitter")
require("jojo.plugins.gitsigns")

